# Generated by Django 4.0.5 on 2022-08-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_more_detail_image_alter_address_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_more_detail',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
