# Generated by Django 4.0.5 on 2022-08-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_order_quantity_product_sold_stock_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('cash', 'cash'), ('debit', 'debit cart'), ('paytm', 'paytm'), ('bank', 'Bank Transfer')], default='', max_length=10),
        ),
    ]
