# Generated by Django 4.0.5 on 2022-09-02 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='user',
        ),
    ]
