# Generated by Django 4.0.5 on 2022-09-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_offer_discount_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='discount_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
