# Generated by Django 4.0.5 on 2022-09-05 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_productrating'),
        ('myapp', '0023_offer_discount_price'),
    ]

    operations = [
    ]
