# Generated by Django 4.0.5 on 2022-08-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_sku',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
