# Generated by Django 4.0.5 on 2022-08-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_user_more_detail_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_more_detail',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10),
        ),
    ]
