# Generated by Django 4.0.5 on 2022-08-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_address_country_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_more_detail',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
