# Generated by Django 4.0.5 on 2022-08-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('none', 'none'), ('cash', 'cash'), ('debit', 'debit cart'), ('paytm', 'paytm'), ('bank', 'Bank Transfer')], default='none', max_length=10),
        ),
    ]
