# Generated by Django 4.0.5 on 2022-08-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('On the way', 'On the way'), ('Refund', 'Refund'), ('Failed', 'Failed')], max_length=20),
        ),
    ]
