# Generated by Django 4.0.5 on 2022-09-05 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_offer_category_alter_offer_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
